root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/memore"
  cmd = "sh ./scripts/build-dev.sh"
  delay = 300
  exclude_dir = ["dist", "tmp", "vendor", ".git"]
  exclude_regex = [".*_templ.go", "_test.go"]
  include_ext = ["go", "templ", "css", "js", "json", "webmanifest", "svg", "png", "jpg", "jpeg", "ttf"]
  kill_delay = "200ms"
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[proxy]
  enabled = true
  app_port = 8080
  proxy_port = 8090

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[misc]
  clean_on_exit = true
